spring:
  datasource:
    url: ${MYSQL_DB_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    mongodb:
      database: blueScreen
      uri: ${MONGODB_URI}
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    extras:
      springsecurity6: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-circular-references: true

#logging:
#  level:
#    root: INFO
#    bluescreensite: DEBUG
#    org.springframework.data.mongodb: DEBUG
#    org.springframework.data.jpa: DEBUG

server:
  port: 8080

file:
  upload-dir: ./uploads